# Generated by Django 5.2.16 on 2026-07-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldprice',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=5, verbose_name='درصد سود'),
        ),
    ]
